---
post:
  select-label:
    template: |
      ## [ACTION REQUIRED] Please select target label
      Please select a deploy target from GitHub label. You can also select more than one.
      The deploy target directory is set in `{{.Vars.DEPLOY_TARGET_FILE}}`

      - `{{.Vars.ALL_LABEL}}`
          - Deploy to all environment (**If multiple labels are included, `{{.Vars.ALL_LABEL}}` takes precedence**)
      - `{{.Vars.PROD_LABEL}}`
          - Deploy to production environment
      - `{{.Vars.STG_LABEL}}`
          - Deploy to staging environment
      - `{{.Vars.DEV_LABEL}}`
          - Deploy to develop environment
