name: "Set matrix job workdir"
description: "The composite actions are used to dynamically create the workdir used by the matrix."

outputs:
  matrix-workdir:
    description: "Terraform working directory"
    value: ${{ steps.set_matrix.outputs.value }}

inputs:
  pr_number:
    required: true
    description: "Pull Request Number"
  deploy_target_file:
    default: ".github/workflows/deploy_target.json" required: false
    description: "path to deply_target.json"
  token:
    default: "${{ github.token }}"
    required: false
    description: "GITHUB_TOKEN"

runs:
  using: "composite"
  steps:
    - name: Install ci-info
      shell: bash
      run: |
        CI_INFO_VERSION=2.0.3
        curl -sSfL -o ci-info.tar.gz https://github.com/suzuki-shunsuke/ci-info/releases/download/v${CI_INFO_VERSION}/ci-info_${CI_INFO_VERSION}_linux_amd64.tar.gz
        sudo tar -C /usr/bin -xzf ./ci-info.tar.gz

    - name: Install github-comment
      shell: bash
      run: |
        GITHUB_COMMENT_VERSION=4.1.1
        sudo curl -sSfL -o github-comment_linux_amd64.tar.gz https://github.com/suzuki-shunsuke/github-comment/releases/download/v${GITHUB_COMMENT_VERSION}/github-comment_${GITHUB_COMMENT_VERSION}_linux_amd64.tar.gz
        sudo tar -C /usr/bin -xzf ./github-comment_linux_amd64.tar.gz

    - name: Set GITHUB_TOKEN
      shell: bash
      run: |
        printf "GITHUB_TOKEN=%s" $(echo ${{ inputs.token }}) >> $GITHUB_ENV

    - name: Run ci-info
      shell: bash
      run: |
        export PR_NUMBER=$(echo ${{ inputs.pr_number }})
        eval $(ci-info run --owner ${GITHUB_REPOSITORY%/*} --repo ${GITHUB_REPOSITORY#*/} --pr "$PR_NUMBER")
        printf "CI_INFO_TEMP_DIR=%s" $(echo $CI_INFO_TEMP_DIR) >> $GITHUB_ENV

    - name: Set Deploy Target
      shell: bash
      id: set_matrix
      run: ${{ github.action_path }}/main.sh
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        DEPLOY_TARGET_FILE: ${{ inputs.deploy_target_file }}
        PR_NUMBER: ${{ inputs.pr_number }}
